import { Link, useParams } from 'react-router';
import { Logo } from '../components/Logo';

type LegalPage = 'terms' | 'privacy' | 'disclaimer';

const PAGES: Record<LegalPage, { title: string; updated: string; content: React.ReactNode }> = {
  terms: {
    title: 'Terms of Service',
    updated: 'April 18, 2026',
    content: (
      <div>
        <Section title="1. Acceptance of Terms">
          <p>By accessing or using Nautilus ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        </Section>
        <Section title="2. Description of Service">
          <p>Nautilus is an art market intelligence platform that provides data aggregation, AI-powered analysis, and investment signal tools. The Service is provided for informational purposes only and does not constitute financial or investment advice.</p>
        </Section>
        <Section title="3. Subscriptions and Billing">
          <p>Nautilus offers subscription plans (Collector, Investor, Family Office) billed monthly or annually. Subscriptions automatically renew unless cancelled. All charges are in EUR. A 30-day money-back guarantee applies to new subscriptions.</p>
          <ul>
            <li>You may cancel at any time through your account settings.</li>
            <li>Refunds are processed within 5–10 business days.</li>
            <li>Plan downgrades take effect at the end of the billing period.</li>
          </ul>
        </Section>
        <Section title="4. Intellectual Property">
          <p>All content, data, analyses, scores, and AI outputs generated by Nautilus are the property of Nautilus. You may not reproduce, redistribute, or commercialize any output without written permission.</p>
        </Section>
        <Section title="5. Prohibited Use">
          <p>You agree not to: scrape or harvest data from the Service; use the Service to build competing products; circumvent access controls; or use the Service for unlawful purposes.</p>
        </Section>
        <Section title="6. Limitation of Liability">
          <p>Nautilus is not liable for any investment decisions made based on information provided by the Service. Past performance of art market signals does not guarantee future results. The Service is provided "as is" without warranties of any kind.</p>
        </Section>
        <Section title="7. Governing Law">
          <p>These Terms are governed by French law. Any disputes shall be subject to the exclusive jurisdiction of the courts of Paris, France.</p>
        </Section>
        <Section title="8. Contact">
          <p>Questions regarding these Terms: <a href="mailto:contact@get-nautilus.com" style={{ color: 'var(--navy)' }}>contact@get-nautilus.com</a></p>
        </Section>
      </div>
    ),
  },
  privacy: {
    title: 'Privacy Policy',
    updated: 'April 18, 2026',
    content: (
      <div>
        <Section title="1. Data Controller">
          <p>Nautilus (operated by its founder) is the controller of your personal data under GDPR (Regulation EU 2016/679).</p>
        </Section>
        <Section title="2. Data We Collect">
          <ul>
            <li><strong>Account data:</strong> name, email address, password (hashed)</li>
            <li><strong>Profile data:</strong> budget range, collector preferences, portfolio entries (declared by you)</li>
            <li><strong>Behavioral data:</strong> lots viewed, searches, time on page, Larry chat history</li>
            <li><strong>Billing data:</strong> handled by Stripe — we do not store card details</li>
            <li><strong>Technical data:</strong> IP address, browser type, device, cookies</li>
          </ul>
        </Section>
        <Section title="3. Legal Basis for Processing">
          <ul>
            <li>Contract performance (delivering the Service you subscribed to)</li>
            <li>Legitimate interest (improving recommendations, preventing fraud)</li>
            <li>Consent (marketing emails — you may withdraw at any time)</li>
          </ul>
        </Section>
        <Section title="4. How We Use Your Data">
          <ul>
            <li>To provide and improve the Service</li>
            <li>To power the AI recommendation engine (CollectorDNA profile)</li>
            <li>To send transactional and marketing emails (with consent)</li>
            <li>To prevent fraud and ensure security</li>
          </ul>
        </Section>
        <Section title="5. Data Sharing">
          <p>We share data with:</p>
          <ul>
            <li><strong>Stripe</strong> — payment processing</li>
            <li><strong>OpenAI</strong> — AI analysis (data processed under OpenAI's data processing agreement)</li>
            <li><strong>Railway / Neon</strong> — infrastructure hosting</li>
            <li><strong>Resend</strong> — email delivery</li>
          </ul>
          <p>We do not sell your personal data to third parties.</p>
        </Section>
        <Section title="6. Your Rights (GDPR)">
          <ul>
            <li><strong>Access</strong> — request a copy of your data</li>
            <li><strong>Rectification</strong> — correct inaccurate data</li>
            <li><strong>Erasure</strong> — request deletion (Art. 17)</li>
            <li><strong>Portability</strong> — export your data (Art. 20) via /app/profile/export</li>
            <li><strong>Objection</strong> — object to processing for marketing</li>
            <li><strong>Restriction</strong> — restrict processing in certain circumstances</li>
          </ul>
          <p>To exercise your rights: <a href="mailto:privacy@get-nautilus.com" style={{ color: 'var(--navy)' }}>privacy@get-nautilus.com</a></p>
        </Section>
        <Section title="7. Data Retention">
          <p>Account data is retained for the duration of your subscription plus 12 months. Upon account deletion, personal data is purged within 30 days. Anonymized aggregate data may be retained indefinitely.</p>
        </Section>
        <Section title="8. Cookies">
          <p>We use strictly necessary cookies (authentication), analytics cookies (with consent), and no advertising cookies. See our <Link to="/legal/cookies" style={{ color: 'var(--navy)' }}>Cookie Policy</Link>.</p>
        </Section>
        <Section title="9. Contact">
          <p>Data protection queries: <a href="mailto:privacy@get-nautilus.com" style={{ color: 'var(--navy)' }}>privacy@get-nautilus.com</a></p>
        </Section>
      </div>
    ),
  },
  disclaimer: {
    title: 'Investment Disclaimer',
    updated: 'April 18, 2026',
    content: (
      <div>
        <div style={{ background: 'rgba(248,113,113,0.06)', border: '1px solid rgba(248,113,113,0.2)', borderRadius: '8px', padding: '20px 24px', marginBottom: '32px' }}>
          <div style={{ fontSize: '13px', fontWeight: 700, color: '#d4183d', fontFamily: 'var(--font-mono)', letterSpacing: '0.1em', marginBottom: '8px' }}>
            IMPORTANT NOTICE
          </div>
          <p style={{ fontSize: '15px', color: 'var(--text)', lineHeight: 1.6, margin: 0 }}>
            Nautilus does not provide financial advice, investment advice, or trading recommendations. All information on this platform is for informational and educational purposes only.
          </p>
        </div>
        <Section title="Not Financial Advice">
          <p>The AI-generated scores, analyses, signals, and recommendations provided by Nautilus are based on historical data and pattern recognition. They do not constitute investment advice, financial advice, or recommendations to buy or sell any artwork or asset.</p>
          <p>You should not make any investment decision based solely on information provided by Nautilus. Always conduct your own due diligence and consult with qualified professionals before making any investment.</p>
        </Section>
        <Section title="No Guarantee of Returns">
          <p>Past performance of art market signals, deal scores, or any other metrics displayed on Nautilus does not guarantee future results. Art markets are illiquid, subjective, and inherently unpredictable. Any investment in art carries the risk of total or partial loss of capital.</p>
        </Section>
        <Section title="Data Accuracy">
          <p>While we strive for accuracy, Nautilus cannot guarantee that all data is complete, accurate, or up to date. Auction house data, price estimates, and artist information may contain errors or be subject to revision.</p>
        </Section>
        <Section title="Regulatory Status">
          <p>Nautilus is not a regulated financial institution, investment firm, or financial adviser under any applicable law. We are not registered with the AMF (Autorité des marchés financiers), the FCA, the SEC, or any other financial regulatory body.</p>
        </Section>
        <Section title="Investment Memo Disclaimer">
          <p>Every Investment Memo generated by Nautilus includes the following notice: "This memo is generated by AI for informational purposes only. It does not constitute financial advice. Nautilus is not a regulated investment adviser. Consult a qualified professional before making any investment decision."</p>
        </Section>
        <Section title="Contact">
          <p>Legal queries: <a href="mailto:contact@get-nautilus.com" style={{ color: 'var(--navy)' }}>contact@get-nautilus.com</a></p>
        </Section>
      </div>
    ),
  },
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '32px' }}>
      <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '20px', fontWeight: 600, color: 'var(--text)', marginBottom: '12px' }}>{title}</h2>
      <div style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>{children}</div>
    </div>
  );
}

export default function Legal() {
  const { page } = useParams<{ page: string }>();
  const legalPage = (page as LegalPage) || 'terms';
  const content = PAGES[legalPage] || PAGES.terms;

  const tabs: { key: LegalPage; label: string }[] = [
    { key: 'terms',      label: 'Terms of Service'     },
    { key: 'privacy',    label: 'Privacy Policy'        },
    { key: 'disclaimer', label: 'Investment Disclaimer' },
  ];

  return (
    <div style={{ background: 'var(--bg)', minHeight: '100vh' }}>

      {/* Header */}
      <header style={{ position: 'sticky', top: 0, zIndex: 50, background: 'rgba(255,255,255,0.97)', backdropFilter: 'blur(12px)', borderBottom: '1px solid var(--border)', height: '64px', padding: '0 40px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <Link to="/" style={{ textDecoration: 'none' }}>
          <Logo variant="horizontal" color="dark" size={24} />
        </Link>
        <div style={{ display: 'flex', gap: '24px' }}>
          <Link to="/app/login" style={{ fontSize: '13px', color: 'var(--text-2)', textDecoration: 'none' }}>Sign in</Link>
          <Link to="/app/signup" style={{ fontSize: '13px', color: 'white', background: 'var(--navy)', padding: '8px 20px', borderRadius: '6px', textDecoration: 'none', fontWeight: 600 }}>
            Get access
          </Link>
        </div>
      </header>

      {/* Content */}
      <div style={{ maxWidth: '840px', margin: '0 auto', padding: '64px 40px' }}>

        {/* Page header */}
        <div style={{ marginBottom: '48px' }}>
          <div style={{ fontSize: '10px', fontWeight: 700, color: 'var(--text-3)', fontFamily: 'var(--font-mono)', letterSpacing: '0.16em', textTransform: 'uppercase', marginBottom: '12px' }}>
            LEGAL
          </div>
          <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: '42px', fontWeight: 700, color: 'var(--text)', marginBottom: '8px' }}>
            {content.title}
          </h1>
          <div style={{ fontSize: '13px', color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>
            Last updated: {content.updated}
          </div>
        </div>

        {/* Tabs */}
        <div style={{ display: 'flex', gap: '4px', marginBottom: '48px', borderBottom: '1px solid var(--border)', paddingBottom: '0' }}>
          {tabs.map(({ key, label }) => (
            <Link
              key={key}
              to={`/legal/${key}`}
              style={{
                padding: '10px 20px',
                fontSize: '13px',
                fontWeight: key === legalPage ? 700 : 400,
                color: key === legalPage ? 'var(--navy)' : 'var(--text-2)',
                textDecoration: 'none',
                borderBottom: key === legalPage ? '2px solid var(--navy)' : '2px solid transparent',
                marginBottom: '-1px',
                whiteSpace: 'nowrap',
              }}
            >
              {label}
            </Link>
          ))}
        </div>

        {/* Body */}
        <div style={{ lineHeight: 1.8 }}>
          {content.content}
        </div>

      </div>

      {/* Footer */}
      <footer style={{ padding: '32px 40px', textAlign: 'center', background: 'var(--bg-subtle)', borderTop: '1px solid var(--border)' }}>
        <div style={{ fontSize: '12px', color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>
          © 2026 Nautilus · Not financial advice · <a href="mailto:contact@get-nautilus.com" style={{ color: 'var(--text-3)', textDecoration: 'none' }}>contact@get-nautilus.com</a>
        </div>
      </footer>
    </div>
  );
}
