"""add_profile_fields

Revision ID: 170a5386e89c
Revises: 0001_initial
Create Date: 2026-03-26 14:41:03.790740
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '170a5386e89c'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('notify_sms', sa.Boolean(), nullable=True))
    op.add_column('preferences', sa.Column('collector_type', sa.String(length=50), nullable=True))
    op.add_column('preferences', sa.Column('investment_horizon', sa.String(length=50), nullable=True))
    op.add_column('preferences', sa.Column('min_lot_budget_eur', sa.Float(), nullable=True))
    op.add_column('preferences', sa.Column('max_lot_budget_eur', sa.Float(), nullable=True))
    op.add_column('preferences', sa.Column('preferred_periods', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('preferences', sa.Column('preferred_regions', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('preferences', 'preferred_regions')
    op.drop_column('preferences', 'preferred_periods')
    op.drop_column('preferences', 'max_lot_budget_eur')
    op.drop_column('preferences', 'min_lot_budget_eur')
    op.drop_column('preferences', 'investment_horizon')
    op.drop_column('preferences', 'collector_type')
    op.drop_column('preferences', 'notify_sms')
    # ### end Alembic commands ###
